# Generated by Django 2.2.6 on 2019-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Current_Job', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=2)),
                ('Email_Address', models.CharField(max_length=100)),
                ('Telephone_Number', models.CharField(max_length=10)),
                ('Employment_History', models.TextField()),
                ('Education', models.TextField()),
                ('Skills', models.TextField()),
                ('Hobbies', models.TextField()),
                ('Internships', models.TextField()),
                ('Referress', models.TextField()),
            ],
        ),
    ]
